# Generated by Django 3.1.7 on 2021-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=2048)),
                ('picture', models.FileField(upload_to='pictures/')),
                ('date_created', models.TimeField(auto_now_add=True)),
                ('source', models.URLField()),
            ],
        ),
    ]
