# Generated by Django 3.1.7 on 2021-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
